In [2]:
!nvidia-smi

Sun Jul 19 16:22:02 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


##Introduction to Tensors
###Creating Tensors

In [4]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#Get tensor back as Python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###Random Tensors

In [18]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3245, 0.2047, 0.3964, 0.2007],
        [0.8731, 0.6684, 0.7299, 0.6335],
        [0.6421, 0.2166, 0.6637, 0.3112]])

In [19]:
random_tensor.ndim

2

In [20]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

####Zeros and Ones

In [21]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [26]:
#Use torch.range()
torch.arange(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [28]:
#Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [29]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor
                               device=None, # What device is tensor on
                               requires_grad=False) # Wheater or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting information from tensors

In [35]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3169, 0.8687, 0.8756, 0.2605],
        [0.1485, 0.5273, 0.9441, 0.5924],
        [0.5108, 0.7558, 0.9039, 0.0272]])

In [36]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [37]:
some_tensor.size()

torch.Size([3, 4])

In [38]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype  of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3169, 0.8687, 0.8756, 0.2605],
        [0.1485, 0.5273, 0.9441, 0.5924],
        [0.5108, 0.7558, 0.9039, 0.0272]])
Datatype  of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating Tensors (tensor operations)

In [39]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
#Muliplication tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
#Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
#Try out PyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])

###Matrix Multiplication

In [44]:
#Element wise muliplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [45]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
#Matrix multiplication by hand
1*1 + 2*2 + 3+3

11

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 927 µs, sys: 171 µs, total: 1.1 ms
Wall time: 4.08 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 245 µs, total: 245 µs
Wall time: 185 µs


tensor(14)

In [49]:
tensor @ tensor

tensor(14)

###One of the most common errors in deep learning: shape errors

In [50]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7,10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for waiting less code)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [51]:
tensor_B.T, tensor_B, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([2, 3]))

In [52]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


##Finding the min, max, mean, sum, etc (tensor aggregation)

In [53]:
#Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [57]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

###Finding the positional min and max

In [58]:
#Find the position in tensor that has the minimum value with argmin()->returns index position of target tensor where the minimum value occurs.
x.argmin()

tensor(0)

In [59]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

###Reshaping, stacking, squeezing and unsqueezing tensors

In [60]:
#Let's create a tensor
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
#Add an extra dimension
y_reshaped = y.reshape(1, 9)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
#Change the view
z = y.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
#Changing z changes y (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [64]:
#Stack tensors on top of each other
y_stacked = torch.stack([y, y, y, y], dim=0)
y_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [65]:
#torch.squeeze() - removes all single dimensions from a target tensor
y_reshaped
y_reshaped.shape


torch.Size([1, 9])

In [66]:
y_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
y_reshaped.squeeze().shape

torch.Size([9])

In [68]:
print(f"Previous tensor: {y_reshaped}")
print(f"Previous shape: {y_reshaped.shape}")

#Remove extra dimensions from y_reshaped
y_squeezed = y_reshaped.squeeze()
print(f"\nNew tensor: {y_squeezed}")
print(f"New shape: {y_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [69]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {y_squeezed}")
print(f"Previous shape: {y_squeezed.shape}")

#Add an extra dimension with unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [70]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, color_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


###Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with Numpy

In [71]:
#Create a tensor
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
#Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
#Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [74]:
#Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [75]:
#You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [76]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [77]:
#Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [78]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [79]:
#Index on x to return 9
x[0][2][2]

tensor(9)

In [80]:
#Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

###PyTorch tensors & NumPy

In [81]:
#NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #Warning: When converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
array.dtype

dtype('float64')

In [83]:
tensor.dtype

torch.float64

In [84]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [85]:
#Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
#Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [87]:
numpy_tensor.dtype

dtype('float32')

In [88]:
#Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproducibility (trying to take random out of random)

In [89]:
#Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0904, 0.7204, 0.3433, 0.9764],
        [0.2540, 0.5361, 0.3244, 0.1735],
        [0.3354, 0.9804, 0.1838, 0.3444]])
tensor([[0.0977, 0.4440, 0.6794, 0.2111],
        [0.8457, 0.8253, 0.6390, 0.2871],
        [0.3581, 0.9387, 0.8603, 0.9350]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
#Let's make some random but reproducible tensors

#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


###Running tensors and PyTorch objects on the GPUs (and making faster computations )

###1. Getting a GPU

###2. Check for GPU access with PyTorch

In [91]:
#Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [92]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [93]:
#Count number of device
torch.cuda.device_count()

1

###3. Putting tensors (and models) on the GPU

In [94]:
#Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [95]:
#Move tensor to GPU (if availabe)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###4. Moving tensors back to the CPU

In [98]:
#If tensor is on GPU, can't transform it to NumPy
#tensor_on_gpu.numpy()

In [99]:
#To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])